export const initialBuildings = [
  {
    id: "cursor",
    name: "Cursor",
    description: "Autoclicks once every 10 seconds.",
    image: "https://i.imgur.com/hgUcjEh.png",
    image_bg: "https://i.imgur.com/hgUcjEh.png",
    image_preview: "https://i.imgur.com/hgUcjEh.png",
    baseCost: 15,
    cps: 1000000.2,
    count: 0,
  },
  {
    id: "grandma",
    name: "Grandma",
    description: "A nice grandma to bake more cookies.",
    image: "https://i.imgur.com/raI4UEF.png",
    image_bg: "https://i.imgur.com/wZr7w2G.png",
    image_preview: "https://i.imgur.com/2OfnoA6.png",
    baseCost: 100,
    cps: 1,
    count: 0,
  },
  {
    id: "farm",
    name: "Farm",
    description: "Grows cookie plants from cookie seeds.",
    image: "https://i.imgur.com/CW3S05B.png",
    image_bg: "https://i.imgur.com/oNNtRl1.png",
    image_preview: "https://i.imgur.com/nObf7GO.png",
    baseCost: 1100,
    cps: 8,
    count: 0,
  },
  {
    id: "mine",
    name: "Mine",
    description: "Mines out cookie dough and chocolate chips.",
    image: "https://i.imgur.com/xOgQZao.png",
    image_bg: "https://i.imgur.com/trNi8qY.png",
    image_preview: "https://i.imgur.com/PlDcB6A.png",
    baseCost: 12000,
    cps: 47,
    count: 0,
  },
  {
    id: "factory",
    name: "Factory",
    description: "Produces large quantities of cookies.",
    image: "https://i.imgur.com/VZ2x4Gc.png",
    image_bg: "https://i.imgur.com/6fZzgX5.png",
    image_preview: "https://i.imgur.com/ZMxGwGt.png",
    baseCost: 130000,
    cps: 260,
    count: 0,
  },
  {
    id: "bank",
    name: "Bank",
    description: "Generates cookies from interest.",
    image: "https://i.imgur.com/zKi48Xc.png",
    image_bg: "https://i.imgur.com/2atr4NF.png",
    image_preview: "https://i.imgur.com/y36PEWq.png",
    baseCost: 1400000,
    cps: 1400,
    count: 0,
  },
  {
    id: "temple",
    name: "Temple",
    description: "Full of precious, ancient chocolate.",
    image: "https://i.imgur.com/sZ6YR4M.png",
    image_bg: "https://imgur.com/IUiZJkU",
    image_preview: "https://imgur.com/ObBhBDY",
    baseCost: 20000000,
    cps: 7800,
    count: 0,
  },
  {
    id: "wizard-tower",
    name: "Wizard Tower",
    description: "Summons cookies with magic spells.",
    image: "https://i.imgur.com/iJYVix2.png",
    image_bg: "https://i.imgur.com/J2GWQqx.png",
    image_preview: "https://i.imgur.com/TZOPmSL.png",
    baseCost: 330000000,
    cps: 44000,
    count: 0,
  },
  

];

export const initialUpgrades = [
  // Click upgrades
  {
    id: "reinforced-index-finger",
    name: "Reinforced Index Finger",
    description: "Cookies per click +1",
    image: "https://i.imgur.com/Lvfvftl.png",
    cost: 100,
    type: "click",
    multiplier: 2,
    purchased: false,
    requiredCookies: 100,
  },
  {
    id: "carpal-tunnel-prevention-cream",
    name: "Carpal Tunnel Prevention Cream",
    description: "Clicking is twice as efficient",
    image: "🧴",
    cost: 500,
    type: "click",
    multiplier: 2,
    purchased: false,
    requiredCookies: 500,
  },
  {
    id: "ambidextrous",
    name: "Ambidextrous",
    description: "Clicking is twice as efficient",
    image: "👐",
    cost: 10000,
    type: "click",
    multiplier: 2,
    purchased: false,
    requiredCookies: 10000,
  },

  // Cursor upgrades
  {
    id: "forwards-from-grandma",
    name: "Forwards from Grandma",
    description: "Cursors are twice as efficient",
    image: "📧",
    cost: 1000,
    type: "building",
    multiplier: 2,
    purchased: false,
    requiredBuilding: { id: "cursor", count: 10 },
    buildingId: "cursor",
  },
  {
    id: "steel-plated-mouse",
    name: "Steel-plated Mouse",
    description: "Cursors are twice as efficient",
    image: "🖱️",
    cost: 5000,
    type: "building",
    multiplier: 2,
    purchased: false,
    requiredBuilding: { id: "cursor", count: 25 },
    buildingId: "cursor",
  },

  // Grandma upgrades
   {
    id: "bingo-center",
    name: "Bingo Center",
    description: "Grandmas are twice as efficient",
    image: "🎮",
    cost: 25000,
    type: "building",
    multiplier: 2,
    purchased: false,
    requiredBuilding: { id: "grandma", count: 25 },
    buildingId: "grandma",
  },

  // Farm upgrades
  {
    id: "cheap-hoes",
    name: "Cactus",
    description: "Farms are twice as efficient",
    image: "🌵",
    cost: 11000,
    type: "building",
    multiplier: 2,
    purchased: false,
    requiredBuilding: { id: "farm", count: 10 },
    buildingId: "farm",
  },
  {
    id: "fertilizer",
    name: "Fertilizer",
    description: "Farms are twice as efficient",
    image: "💩",
    cost: 55000,
    type: "building",
    multiplier: 2,
    purchased: false,
    requiredBuilding: { id: "farm", count: 25 },
    buildingId: "farm",
  },

  // Mine upgrades
  {
    id: "sugar-gas",
    name: "Sugar Gas",
    description: "Mines are twice as efficient",
    image: "💨",
    cost: 120000,
    type: "building",
    multiplier: 2,
    purchased: false,
    requiredBuilding: { id: "mine", count: 10 },
    buildingId: "mine",
  },
  {
    id: "megadrill",
    name: "Megadrill",
    description: "Mines are twice as efficient",
    image: "🔩",
    cost: 600000,
    type: "building",
    multiplier: 2,
    purchased: false,
    requiredBuilding: { id: "mine", count: 25 },
    buildingId: "mine",
  },

  // Factory upgrades
  {
    id: "sturdier-conveyor-belts",
    name: "Sturdier Conveyor Belts",
    description: "Factories are twice as efficient",
    image: "➡️",
    cost: 1300000,
    type: "building",
    multiplier: 2,
    purchased: false,
    requiredBuilding: { id: "factory", count: 10 },
    buildingId: "factory",
  },
  {
    id: "child-labor",
    name: "Child Labor",
    description: "Factories are twice as efficient",
    image: "👶",
    cost: 6500000,
    type: "building",
    multiplier: 2,
    purchased: false,
    requiredBuilding: { id: "factory", count: 25 },
    buildingId: "factory",
  },

  // Global upgrades
  {
    id: "sugar-coating",
    name: "Sugar Coating",
    description: "All buildings are 10% more efficient",
    image: "🍬",
    cost: 99999,
    type: "global",
    multiplier: 1.1,
    purchased: false,
    requiredCookies: 50000,
  },
  {
    id: "lucky-day",
    name: "Lucky Day",
    description: "All buildings are 15% more efficient",
    image: "🍀",
    cost: 777777,
    type: "global",
    multiplier: 1.15,
    purchased: false,
    requiredCookies: 500000,
  },
  {
    id: "divine-bakery",
    name: "Divine Bakery",
    description: "All buildings are 20% more efficient",
    image: "😇",
    cost: 9999999,
    type: "global",
    multiplier: 1.2,
    purchased: false,
    requiredCookies: 5000000,
  },

  // news:
    // Click upgrades
  {
    id: "golden-touch",
    name: "Golden Touch",
    description: "Clicking power increased by 5x",
    image: "🤲✨",
    cost: 50000,
    type: "click",
    multiplier: 5,
    purchased: false,
    requiredCookies: 50000,
  },
  {
    id: "quantum-clicking",
    name: "Quantum Clicking",
    description: "Clicks generate extra cookies over time",
    image: "⚛️",
    cost: 250000,
    type: "click",
    multiplier: 1.2,
    purchased: false,
    requiredCookies: 250000,
  },

  // Cursor upgrades
  {
    id: "ai-assisted-clicking",
    name: "AI-Assisted Clicking",
    description: "Cursors generate 50% more cookies",
    image: "🤖",
    cost: 20000,
    type: "building",
    multiplier: 1.5,
    purchased: false,
    requiredBuilding: { id: "cursor", count: 50 },
    buildingId: "cursor",
  },

  // Grandma upgrades
  {
    id: "grandma-union",
    name: "Grandma Union",
    description: "Grandmas work 50% faster",
    image: "🛠️",
    cost: 75000,
    type: "building",
    multiplier: 1.5,
    purchased: false,
    requiredBuilding: { id: "grandma", count: 50 },
    buildingId: "grandma",
  },

  // Farm upgrades
  {
    id: "hydroponic-farms",
    name: "Hydroponic Farms",
    description: "Farms generate 50% more cookies",
    image: "💧🌱",
    cost: 200000,
    type: "building",
    multiplier: 1.5,
    purchased: false,
    requiredBuilding: { id: "farm", count: 50 },
    buildingId: "farm",
  },

  // Mine upgrades
  {
    id: "deep-earth-extraction",
    name: "Deep Earth Extraction",
    description: "Mines generate 50% more cookies",
    image: "⛏️",
    cost: 750000,
    type: "building",
    multiplier: 1.5,
    purchased: false,
    requiredBuilding: { id: "mine", count: 50 },
    buildingId: "mine",
  },

  // Factory upgrades
  {
    id: "automated-assembly",
    name: "Automated Assembly",
    description: "Factories generate 50% more cookies",
    image: "🏭🤖",
    cost: 1500000,
    type: "building",
    multiplier: 1.5,
    purchased: false,
    requiredBuilding: { id: "factory", count: 50 },
    buildingId: "factory",
  },

  // Global upgrades
  {
    id: "cookie-stock-market",
    name: "Cookie Stock Market",
    description: "All buildings are 25% more efficient",
    image: "📈🍪",
    cost: 20000000,
    type: "global",
    multiplier: 1.25,
    purchased: false,
    requiredCookies: 10000000,
  },
  {
    id: "galactic-bakery",
    name: "Galactic Bakery",
    description: "All buildings are 30% more efficient",
    image: "🚀🍪",
    cost: 50000000,
    type: "global",
    multiplier: 1.3,
    purchased: false,
    requiredCookies: 25000000,
  },
]

export const achievements = [
  // Cookie achievements
  {
    id: "wake-and-bake",
    name: "Wake and Bake",
    description: "Bake 1 cookie",
    image: "🍪",
    type: "cookies",
    threshold: 1,
    unlocked: false,
  },
  {
    id: "casual-baking",
    name: "Casual Baking",
    description: "Bake 1,000 cookies",
    image: "🍪",
    type: "cookies",
    threshold: 1000,
    unlocked: false,
  },
  {
    id: "hardcore-baking",
    name: "Hardcore Baking",
    description: "Bake 10,000 cookies",
    image: "🍪",
    type: "cookies",
    threshold: 10000,
    unlocked: false,
  },
  {
    id: "steady-tasty-stream",
    name: "Steady Tasty Stream",
    description: "Bake 100,000 cookies",
    image: "🍪",
    type: "cookies",
    threshold: 100000,
    unlocked: false,
  },
  {
    id: "cookie-monster",
    name: "Cookie Monster",
    description: "Bake 1,000,000 cookies",
    image: "🍪",
    type: "cookies",
    threshold: 1000000,
    unlocked: false,
  },
  {
    id: "mass-producer",
    name: "Mass Producer",
    description: "Bake 10,000,000 cookies",
    image: "🍪",
    type: "cookies",
    threshold: 10000000,
    unlocked: false,
  },
  {
    id: "cookie-vortex",
    name: "Cookie Vortex",
    description: "Bake 100,000,000 cookies",
    image: "🌀",
    type: "cookies",
    threshold: 100000000,
    unlocked: false,
  },

  // Building achievements
  {
    id: "clicktastic",
    name: "Clicktastic",
    description: "Have 1 cursor",
    image: "👆",
    type: "building",
    threshold: 1,
    buildingId: "cursor",
    unlocked: false,
  },
  {
    id: "clickathlon",
    name: "Clickathlon",
    description: "Have 25 cursors",
    image: "👆",
    type: "building",
    threshold: 25,
    buildingId: "cursor",
    unlocked: false,
  },
  {
    id: "clickageddon",
    name: "Clickageddon",
    description: "Have 50 cursors",
    image: "👆",
    type: "building",
    threshold: 50,
    buildingId: "cursor",
    unlocked: false,
  },
  {
    id: "grandma-apprentice",
    name: "Grandma's Apprentice",
    description: "Have 1 grandma",
    image: "👵",
    type: "building",
    threshold: 1,
    buildingId: "grandma",
    unlocked: false,
  },
  {
    id: "retirement-home",
    name: "Retirement Home",
    description: "Have 25 grandmas",
    image: "👵",
    type: "building",
    threshold: 25,
    buildingId: "grandma",
    unlocked: false,
  },
  {
    id: "friend-of-the-ancients",
    name: "Friend of the Ancients",
    description: "Have 50 grandmas",
    image: "👵",
    type: "building",
    threshold: 50,
    buildingId: "grandma",
    unlocked: false,
  },
  {
    id: "green-thumb",
    name: "Green Thumb",
    description: "Have 1 farm",
    image: "🌾",
    type: "building",
    threshold: 1,
    buildingId: "farm",
    unlocked: false,
  },
  {
    id: "my-first-farm",
    name: "My First Farm",
    description: "Have 25 farms",
    image: "🌾",
    type: "building",
    threshold: 25,
    buildingId: "farm",
    unlocked: false,
  },
  {
    id: "reap-what-you-sow",
    name: "Reap What You Sow",
    description: "Have 50 farms",
    image: "🌾",
    type: "building",
    threshold: 50,
    buildingId: "farm",
    unlocked: false,
  },
  {
    id: "excavation-site",
    name: "Excavation Site",
    description: "Have 1 mine",
    image: "⛏️",
    type: "building",
    threshold: 1,
    buildingId: "mine",
    unlocked: false,
  },
  {
    id: "hollow-the-planet",
    name: "Hollow the Planet",
    description: "Have 25 mines",
    image: "⛏️",
    type: "building",
    threshold: 25,
    buildingId: "mine",
    unlocked: false,
  },
  {
    id: "industrious",
    name: "Industrious",
    description: "Have 1 factory",
    image: "🏭",
    type: "building",
    threshold: 1,
    buildingId: "factory",
    unlocked: false,
  },
  {
    id: "global-warming",
    name: "Global Warming",
    description: "Have 25 factories",
    image: "🏭",
    type: "building",
    threshold: 25,
    buildingId: "factory",
    unlocked: false,
  },
]

